name: CI

on:
  push:
    branches: [ main, CI-demo-section-25, CI-demo-section-26 ]
  pull_request:
    branches: [ main, CI-demo-section-25, CI-demo-section-26 ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      #with: 
      #  submodules: recursive

    # Here is how you run terminal commands using GitHub workflows
    - name: output text to the terminal using echo
      run: echo I just ran the echo command in the terminal

    # Compile and run the Hello World program
    - name: Hello World
      run: |
       g++ HelloWorld.cpp -o HelloWorld
       ./HelloWorld

    # git submodule update --init --recursive
